pub(crate) const PRODUCT_NAME: &str = "Anchor";
pub(crate) const SERVER_NAME: &str = "anchor";
pub(crate) const ACTIONS_SERVER_NAME: &str = "anchor-actions";
#[cfg(feature = "cli")]
pub(crate) const CLI_NAME: &str = "anchor";
#[cfg(any(target_os = "macos", test))]
pub const DESKTOP_EXECUTABLE_NAME: &str = "anchor-desktop";
#[cfg(any(target_os = "macos", test))]
pub const BUNDLE_ID: &str = "com.anchor.desktop";
pub(crate) const APP_CONFIG_DIR_NAME: &str = "anchor";
pub(crate) const CONFIG_DIR_ENV: &str = "ANCHOR_CONFIG_DIR";
pub(crate) const LEGACY_APP_CONFIG_DIR_NAME: &str = "coding-tools-mcp-desktop";
pub(crate) const LEGACY_CONFIG_DIR_ENV: &str = "CODING_TOOLS_MCP_CONFIG_DIR";
